### PR TITLE
add missing V5 methods

### PR DESCRIPTION
**Pull request by kshnurov**

### CODE REVIEW

**Comment by kshnurov** [comment]
@rikkimongoose thank you! RubyGems is still v0.2.6, can you update it?

**Comment by rikkimongoose** [comment]
Yes, I will.

**Comment by kshnurov** [comment]
@rikkimongoose still 0.2.6 on RubyGems

**Comment by rikkimongoose** [comment]
I'm sorry, I'll check it

**Comment by rikkimongoose** [comment]
https://rubygems.org/gems/ya-api-direct - 0.2.10 is published!

**Pull request merged**
